# Generated by Django 5.2.4 on 2025-07-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FakePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Learn and Share', max_length=200)),
                ('hero_subtitle', models.TextField(default='Learn practically and effectively with TrackMyJourney—a cybersecurity hub for tracking goals, documenting achievements, and sharing technical insights!')),
                ('about_text', models.TextField(default='TrackMyJourney is a dedicated cybersecurity learning platform...')),
                ('goal_text', models.TextField(default='Our goal is to bridge the gap between learning and practical application...')),
                ('users_count', models.IntegerField(default=20000)),
                ('collaborations_count', models.IntegerField(default=300)),
                ('phone', models.CharField(default='+880 1925292827', max_length=20)),
                ('email', models.EmailField(default='mahathir.khandaker.mk@mail.com', max_length=254)),
                ('address', models.CharField(default='Chottogram, BD', max_length=200)),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
    ]
