# Generated by Django 5.2.4 on 2025-07-07 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tutorial', 'Tutorial'), ('documentation', 'Documentation'), ('tool', 'Tool'), ('template', 'Template'), ('course', 'Course'), ('book', 'Book'), ('video', 'Video'), ('article', 'Article'), ('dataset', 'Dataset'), ('code', 'Code Sample'), ('other', 'Other')], default='other', max_length=20)),
                ('resource_type', models.CharField(choices=[('file', 'File Upload'), ('link', 'External Link'), ('document', 'Document'), ('video', 'Video'), ('image', 'Image'), ('archive', 'Archive'), ('other', 'Other')], default='file', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/files/')),
                ('url', models.URLField(blank=True, help_text='External resource URL', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('is_public', models.BooleanField(default=True, help_text='Make this resource publicly visible')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='resources.resourcecomment')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['category', '-uploaded_at'], name='resources_r_categor_ca33ae_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_public', '-uploaded_at'], name='resources_r_is_publ_e3cfa7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcerating',
            unique_together={('resource', 'user')},
        ),
    ]
