# Generated by Django 5.2.4 on 2025-07-21 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='resourcerating',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='resources_r_categor_ca33ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='resources_r_is_publ_e3cfa7_idx',
        ),
        migrations.AlterUniqueTogether(
            name='resourcerating',
            unique_together={('user', 'resource')},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='resourcecomment',
            name='parent',
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('other', 'Other')], default='document', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('article', 'Article'), ('tutorial', 'Tutorial'), ('template', 'Template'), ('guide', 'Guide'), ('tool', 'Tool'), ('presentation', 'Presentation'), ('research', 'Research Paper'), ('webinar', 'Webinar'), ('podcast', 'Podcast'), ('ebook', 'E-book'), ('infographic', 'Infographic'), ('checklist', 'Checklist'), ('worksheet', 'Worksheet'), ('case_study', 'Case Study'), ('report', 'Report'), ('course', 'Course'), ('software', 'Software'), ('dataset', 'Dataset'), ('code', 'Code Snippet'), ('other', 'Other')], default='article', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'productivity, learning, tech')", max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, help_text='External URL if no file is uploaded (e.g., YouTube link)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resourcerating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='resourcerating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcebookmark',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource'),
        ),
        migrations.AddField(
            model_name='resourcebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcelike',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource'),
        ),
        migrations.AddField(
            model_name='resourcelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='resourcebookmark',
            unique_together={('user', 'resource')},
        ),
        migrations.AlterUniqueTogether(
            name='resourcelike',
            unique_together={('user', 'resource')},
        ),
    ]
